#!/usr/bin/env php
<?php

//define('ROOT', dirname(__FILE__).'/');

//if (is_readable(ROOT.'/function.php')) {
//  require_once ROOT.'/function.php';
//}
//vdump(ROOT);
require_once(__DIR__.'/console/cli.php');

